TEAM NAME : EXTRACT TRANSFORM LOAD
PROJECT NAME : ETL
TEAM NUMBER : 22
PROJECT NUMBER : 28
CLIENT :SREEKANTH PURAM (CIE)
MENTOR :JUHI TANDON

TEAM MEMBERS:
AVINASH KALIVARAPU
T.V.RAVI TEJA
SOWMITH M
ABDULLA S
